version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    # Note: This file works with both Docker and Podman
    # For Podman: podman-compose up -d
    # For Docker: docker-compose -f docker-compose.prod.yml up -d
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - ELASTICSEARCH_INDEX=${ELASTICSEARCH_INDEX}
      - ELASTICSEARCH_USE_SSL=${ELASTICSEARCH_USE_SSL}
      - ELASTICSEARCH_CLOUD_ID=${ELASTICSEARCH_CLOUD_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
      - DEMO_MODE=${DEMO_MODE}
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 